-- =====================================================================
-- CAA · MIGRAÇÃO 1 · TABELAS DO DER
-- ---------------------------------------------------------------------
-- Este arquivo cria EXATAMENTE as 7 tabelas do DER oficial do grupo
-- (arquivo "DER - Peter Chan" / "Código do DER" no Drive):
--
--   Entidades ............ usuario, frase, categoria, palavras_pecs
--   Relacionamentos N:N .. cria, contem, tem
--
-- Nenhuma coluna foi inventada. O que foi adicionado são apenas
-- REGRAS (constraints) que protegem os dados, por exemplo:
--   * "email" não pode se repetir (cada pessoa tem uma conta só);
--   * "perfil" e "tipo_frase" só aceitam valores conhecidos;
--   * se uma frase for apagada, as ligações dela somem junto (cascade).
--
-- Sobre datas: o DER pede "timestamp". Usamos "timestamptz", que é o
-- timestamp COM fuso horário. Assim 15h em São Paulo continua sendo
-- 15h quando a tela mostra o histórico.
--
-- Parábola: pense no banco como um ARMÁRIO com 7 GAVETAS.
-- As 4 gavetas grandes guardam "coisas" (pessoas, frases, figuras,
-- categorias). As 3 gavetas pequenas guardam só "etiquetas de ligação"
-- dizendo quem está ligado com quem.
-- =====================================================================


-- ---------------------------------------------------------------------
-- ENTIDADE USUARIO
-- Guarda quem usa a plataforma (responsável, profissional ou a própria
-- pessoa autista).
-- ---------------------------------------------------------------------
create table public.usuario (
  -- "identity" = o próprio banco escolhe o próximo número (1, 2, 3...),
  -- como a senha de atendimento de uma padaria.
  id_usuario    integer generated by default as identity primary key,
  perfil        varchar(20)  not null
                check (perfil in ('responsavel', 'profissional', 'autista')),
  -- O e-mail liga esta linha à conta de login do Supabase Auth.
  -- Sempre em minúsculas, para "Ana@Email.com" e "ana@email.com"
  -- não virarem duas pessoas diferentes.
  email         varchar(255) not null unique check (email = lower(email)),
  -- SEGURANÇA: a senha verdadeira NUNCA fica aqui. Ela é guardada
  -- criptografada (bcrypt) pelo Supabase Auth, na tabela interna
  -- auth.users. Mantemos a coluna para respeitar o DER, mas ela fica
  -- sempre vazia (NULL). Ninguém consegue ler uma senha a partir daqui.
  senha         varchar(255) default null,
  data_nasc     date,
  nome_completo varchar(120) not null
);

comment on table  public.usuario       is 'Entidade USUARIO do DER.';
comment on column public.usuario.senha is 'Sempre NULL: a senha real fica criptografada no Supabase Auth (auth.users).';


-- ---------------------------------------------------------------------
-- ENTIDADE FRASE
-- Cada vez que alguém monta uma mensagem e toca em "Salvar", nasce
-- uma frase.
-- ---------------------------------------------------------------------
create table public.frase (
  id_frase     integer generated by default as identity primary key,
  data_criacao timestamptz not null default now(),
  -- tipo_frase classifica a intenção da mensagem:
  --   pedido .......... "Eu quero água"
  --   pergunta ........ "Onde mamãe?"
  --   necessidade ..... "Me ajuda", "Não", "Dor"
  --   expressao ....... "Eu feliz", "Gosto música"
  tipo_frase   varchar(20) not null default 'expressao'
               check (tipo_frase in ('pedido', 'pergunta', 'necessidade', 'expressao'))
);

comment on table public.frase is 'Entidade FRASE do DER.';


-- ---------------------------------------------------------------------
-- ENTIDADE CATEGORIA
-- Agrupa as figuras por assunto (Comidas, Sentimentos...) e também
-- pelas cores da chave de Fitzgerald (ações = verde etc.).
-- ---------------------------------------------------------------------
create table public.categoria (
  id_categoria   integer generated by default as identity primary key,
  nome_categoria varchar(80) not null unique,
  desc_categoria text
);

comment on table public.categoria is 'Entidade CATEGORIA do DER.';


-- ---------------------------------------------------------------------
-- ENTIDADE PALAVRAS (PECS)
-- Cada figura PECS: o texto falado e o caminho da imagem.
-- ---------------------------------------------------------------------
create table public.palavras_pecs (
  id_palavra  integer generated by default as identity primary key,
  txt_palavra varchar(80)  not null,
  -- Caminho da imagem dentro do site, ex.: assets/pcs/pcs-p01-12.png
  imagem_pecs varchar(255) not null
);

comment on table public.palavras_pecs is 'Entidade PALAVRAS (PECS) do DER.';


-- ---------------------------------------------------------------------
-- RELACIONAMENTO CRIA (N:N entre USUARIO e FRASE)
-- "Quem criou qual frase", com a data e quantas figuras ela tem.
-- ---------------------------------------------------------------------
create table public.cria (
  id_usuario   integer not null references public.usuario (id_usuario) on delete cascade,
  id_frase     integer not null references public.frase   (id_frase)   on delete cascade,
  data_frase   timestamptz not null default now(),
  qtd_palavras integer   not null check (qtd_palavras between 1 and 40),
  -- A mesma pessoa não "cria" a mesma frase duas vezes.
  primary key (id_usuario, id_frase)
);

comment on table public.cria is 'Relacionamento CRIA (N:N) entre USUARIO e FRASE.';


-- ---------------------------------------------------------------------
-- RELACIONAMENTO CONTEM (N:N entre FRASE e PALAVRAS_PECS)
-- Quais figuras formam cada frase.
-- Sem chave primária de propósito: assim a mesma figura pode aparecer
-- duas vezes na mesma frase ("mais, mais!"), como a criança tocou.
-- ---------------------------------------------------------------------
create table public.contem (
  id_frase   integer not null references public.frase         (id_frase)   on delete cascade,
  id_palavra integer not null references public.palavras_pecs (id_palavra) on delete cascade
);

comment on table public.contem is 'Relacionamento CONTÉM (N:N) entre FRASE e PALAVRAS (PECS).';


-- ---------------------------------------------------------------------
-- RELACIONAMENTO TEM (N:N entre CATEGORIA e PALAVRAS_PECS)
-- Em quais categorias cada figura aparece.
-- data_criacao também define a ORDEM das figuras dentro da categoria
-- (quem foi ligado primeiro aparece primeiro).
-- ---------------------------------------------------------------------
create table public.tem (
  id_categoria integer not null references public.categoria     (id_categoria) on delete cascade,
  id_palavra   integer not null references public.palavras_pecs (id_palavra)   on delete cascade,
  data_criacao timestamptz not null default now(),
  primary key (id_categoria, id_palavra)
);

comment on table public.tem is 'Relacionamento TEM (N:N) entre CATEGORIA e PALAVRAS (PECS).';


-- ---------------------------------------------------------------------
-- ÍNDICES = "sumário do livro". Não mudam os dados, só deixam as
-- buscas mais rápidas (ex.: achar todas as frases de um usuário).
-- ---------------------------------------------------------------------
create index idx_cria_id_frase    on public.cria   (id_frase);
create index idx_contem_id_frase  on public.contem (id_frase);
create index idx_contem_id_palavra on public.contem (id_palavra);
create index idx_tem_id_palavra   on public.tem    (id_palavra);
